### ISSUE TITLE
Does logLevel settings override default settings?

### ISSUE THREAD

**Issue by fanweixiao** [TopCloud/socketcluster#73] opened 2015-05-21 12:56 UTC
If setting `loglevel=3` and start koajs project by `DEBUG=* iojs server.js`, there was no log output.

**Comment by jondubois** [comment] 2015-05-21 13:27
@fanweixiao Yes, that was caused by some old code carried over from SC1 - Like you suggested, it was overwriting the DEBUG env variable which is bad. It has been fixed.

It's been fixed in v2.2.22.
Thanks for reporting!

**Closed by jondubois** 2015-05-21 13:27 UTC
